### PR TITLE
ingressClassname → ingressClassName

### PR DESCRIPTION
**Pull request by jmnote**
ingressClassname → ingressClassName

### CODE REVIEW

**Review by santinoncs — APPROVED** [review]

**Comment by santinoncs** [comment]
Can you bump the Chart.yaml ?

**Comment by phoenix-bjoern** [comment]
@santinoncs the version in Chart.yaml already has been bumped in #30. Since 0.13.0 hasn't been released yet, IMHO there is no need to bump another version for merging this PR.

**Comment by phoenix-bjoern** [comment]
@santinoncs could you tag the 0.13.0 release and publish the new Helm chart version? I'm eager to update our depending charts for the new version ;-)

**Comment by santinoncs** [comment]
let me do that!

**Pull request merged**
